export const storeProducts = [
  {
    id: 1,
    title: "BMW DRIFT STAN IGLA",
    img: "img/product-1.jpg",
    price: 11,
    brand: "BMW",
    model: "E46",
    power: 120,
    engine: 2,
    author_id:"Seba",
    description:
      "Sprzedam bmw po zmianie silnika z 2.0 na 2.5 r6 193hp po modyfikacji sterownika około 205hp. Spaw 100%, kat wycięte,silnik z e39 z przebiegiem 230 tyś km.Miesiąc temu skończony swap także nie katowany.Instalacja LPG wbita w dowód możliwość taniego podłączenia około 300 zł(ja nie podłączałem ponieważ samochodem dojeżdżalem blisko do pracy) Sprzęgło luk obite kevlarem.Tydzien temu zamontowana porządna hydrołapa nie jakiś chinczyk. Ogólnie bawarka podaje jak szalona nawet na 3 biegu. idealna na sezon. Więcej informacji podam przez telefon.",
    color:"baby blue",
    fuel:"benzyna",
    transmission:"10",
    technical_state:"good",
    country_origin:"Germany",
    location:"Ozorkow",
    inFavourites: false,
    count: 1,
    total: 0
  },
  {
    id: 2,
    title: "BMW e36 NOWE Z SALONU",
    img: "img/product-2.jpg",
    price: 12,
    brand: "BMW",
    model: "E46",
    power: 110,
    engine: 1.8,
    author_id:"Janek",
    description:
      "Witam, sprzedam BMW E46 kombi 2.0d 150km. Samochód raz odpala, raz nie. Nie znam się i mam pojęcia co jest zepsute. Blacharsko trochę zmęczona. Przód i tył w m- pakiecie, czarna podsufitka w ładnym stanie, kierownica multi- funkcja działa, oryginalne radio - piksele nie rozlane. Odbiór na lawecie. Brak PT",
    color:"czarne",
    fuel:"gaz",
    transmission:"8",
    technical_state:"dobry",
    country_origin:"Holandia",
    location:"Zgierz",
    inFavourites: false,
    count: 1,
    total: 0
  },
  {
    id: 3,
    title: "BMW GRUZ OKAZJA",
    img: "img/product-3.jpg",
    price: 13,
    brand: "BMW",
    model: "E46",
    power: 120,
    engine: 2,
    author_id:"Seba",
    description:
      "jedzi i skreca",
    color:"baby blue",
    fuel:"gas grass or ass",
    transmission:"10",
    technical_state:"good",
    country_origin:"Germany",
    location:"Ozorkow",
    inFavourites: false,
    count: 1,
    total: 0
  },
  {
    id: 4,
    title: "Driftowuz",
    img: "img/product-4.jpg",
    price: 14,
    brand: "BMW",
    model: "E46",
    power: 120,
    engine: 2,
    author_id:"Seba",
    description:
      "jedzi i skreca",
    color:"baby blue",
    fuel:"gas grass or ass",
    transmission:"10",
    technical_state:"good",
    country_origin:"Germany",
    location:"Ozorkow",
    inFavourites: false,
    count: 1,
    total: 0
  },
  {
    id: 5,
    title: "Piekne BMW, garazowane oazkazja lodzkie!!!!",
    img: "img/product-5.jpg",
    price: 15,
    brand: "BMW",
    model: "E46",
    power: 120,
    engine: 2,
    author_id:"Seba",
    description:
      "jedzi i skreca",
    color:"baby blue",
    fuel:"gas grass or ass",
    transmission:"10",
    technical_state:"good",
    country_origin:"Germany",
    location:"Ozorkow",
    inFavourites: false,
    count: 1,
    total: 0
  },
  {
    id: 6,
    title: "BMW gotowe DO OPALANIA BRUUUM",
    img: "img/product-6.jpg",
    price: 16,
    brand: "BMW",
    model: "E46",
    power: 120,
    engine: 2,
    author_id:"Seba",
        description:
      "jedzi i skreca",
    color:"baby blue",
    fuel:"gas grass or ass",
    transmission:"10",
    technical_state:"good",
    country_origin:"Germany",
    location:"Ozorkow",
    inFavourites: false,
    count: 1,
    total: 0
  },
  {
    id: 7,
    title: "BETKA AUUUU",
    img: "img/product-7.jpg",
    price: 17,
    brand: "BMW",
    model: "E46",
    power: 120,
    engine: 2,
    author_id:"Seba",
        description:
      "jedzi i skreca",
    color:"baby blue",
    fuel:"gas grass or ass",
    transmission:"10",
    technical_state:"good",
    country_origin:"Germany",
    location:"Ozorkow",
    inFavourites: false,
    count: 1,
    total: 0
  },
  {
    id: 8,
    title: "Sportowy samochod dla mlodych",
    img: "img/product-8.jpg",
    price: 18,
    brand: "BMW",
    model: "E46",
    power: 120,
    engine: 2,
    author_id:"Seba",
        description:
      "jedzi i skreca",
    color:"baby blue",
    fuel:"gas grass or ass",
    transmission:"10",
    technical_state:"good",
    country_origin:"Germany",
    location:"Ozorkow",
    inFavourites: false,
    count: 1,
    total: 0
  }
];

export const detailProduct = {
  id: 1,
  title: "BMW DRIFT STAN IGLA",
  img: "img/product-1.jpg",
  price: 11,
  brand: "BMW",
  model: "E46",
  power: 120,
  engine: 2,
  author_id:"Seba",
  description:
    "Sprzedam bmw po zmianie silnika z 2.0 na 2.5 r6 193hp po modyfikacji sterownika około 205hp. Spaw 100%, kat wycięte,silnik z e39 z przebiegiem 230 tyś km.Miesiąc temu skończony swap także nie katowany.Instalacja LPG wbita w dowód możliwość taniego podłączenia około 300 zł(ja nie podłączałem ponieważ samochodem dojeżdżalem blisko do pracy) Sprzęgło luk obite kevlarem.Tydzien temu zamontowana porządna hydrołapa nie jakiś chinczyk. Ogólnie bawarka podaje jak szalona nawet na 3 biegu. idealna na sezon. Więcej informacji podam przez telefon.",
  color:"baby blue",
  fuel:"benzyna",
  transmission:"10",
  technical_state:"Dobry",
  country_origin:"Niemcy",
  location:"Ozorków",
  inFavourites: false,
  count: 1,
  total: 0
};
